### ISSUE TITLE
Hogyan kell letölteni a projektet?

### ISSUE THREAD

**Issue by B4ited** [B4ited/black_jack#2]
Nem tudom letölteni a projektet

**Comment by Richard199815** [comment]
Szia!
Miután letöltötted git-et. Választasz neki egy tetszőleges helyet ahová leszeretnéd tölteni
Azután jobb gomb git bash

Beírod hogy git init

Beírod hogy  git clone https://github.com/B4ited/black_jack.git

**Comment by B4ited** [comment]
Sikerült köszi!
